:PROPERTIES:
:ID:       dc0b9abe-cbe1-4958-8c14-3f899a9cdca4
:END:
#+title: Don't chase the side product

Recently I came cross a great quote by H. David Thoreau:

#+begin_quote
"Success usually comes to those who are too busy to be looking for it".
#+end_quote

I think it's great in that I believe its underlying logic or rationale. In my perspective, success is only a side product. A lot of things people are pursuing, wealth, fame, or even happiness, are just side products. They are the side products that would be more likely to come when we pursue things that truly matters to us, or to others -- the main product. You can't get the side products by chasing only the side products themselves, because the definition of the word "side product" won't allow that to happen, otherwise they are not side products at all. So, many people's pursuits actually don't make any sense to me. What they are chasing is just like flowers in a mirror or the moon's reflection in water.

So what should be the main product? You may ask. Well, I believe this is a question that everyone should ask themselves.
